[package]
name = "project"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk = { version = "0.10.1", package = "gtk4", features = ["v4_14"] }
glib = "0.21.3"
pango = "0.21.3"
pangocairo = "0.21.2"
